pipeline {
    agent {
        node {
            label 'AGENT-1'
        }
    }
    options {
        ansiColor('xterm')
    }
    parameters {
        choice(name: 'action', choices: ['apply', 'destroy'], description: 'Pick something')
    }
    // build
    stages {
        stage('Init') {
             when {
                expression {
                    params.action == 'apply'
                }
            }
            steps {
                sh '''
                    cd 01-vpc
                    terraform init -reconfigure
                '''
            }
        }
        stage('Plan') {
             when {
                expression {
                    params.action == 'apply'
                }
            }
            steps {
                sh '''
                    cd 01-vpc
                    terraform plan
                '''
            }
        }
        stage('Deploy') {
            when {
                expression {
                    params.action == 'apply'
                }
            }
            input {
                message 'Should we continue?'
                ok 'Yes, we should.'
            
            }
            steps {
                sh '''
                    cd 01-vpc
                    terraform apply -auto-approve
                '''
            }
        }
        stage('Destroy') {
            when {
                expression {
                    params.action == 'destroy'
                }
            }
            input {
                message 'Should we continue?'
                ok 'Yes, we should.'
            
            }
            steps {
                sh '''
                    cd 01-vpc
                    terraform destroy -auto-approve
                '''
            }
        }
    }
    // post build
    post {
        always {
            echo 'I will always say Hello again!'
        }
        failure {
            echo 'this runs when pipeline is failed, used generally to send some alerts'
        }
        success {
            echo 'I will say Hello when pipeline is success'
        }
    }
}
