pipeline {
    agent {
        node {
            label 'AGENT-1' // Corrected syntax: 'label' instead of '='
        }
    }
    options{
         timeout(time: 120, unit: 'SECONDS')
        disableConcurrentBuilds()
    }

    stages {
        stage('Init') {
            steps {
                sh """
                cd siva-terraform

                terraform init -reconfigure
                """
            }
        }
        stage('plan') {
            steps {
                sh """
                terraform plan
                """
            }
        }
       
        stage('apply') {
            input{
                message"should we continue"
                ok"go a head"

            }
            steps {
                sh """
                  terraform apply -auto-approve
                """
            }
        }
    }
    post {
        always {
            echo 'will run always'
        }
        failure {
            echl "I will run on failuer"
        }
        success{
            echo "I will run on scuuess inly"
        }
    }
}

